type: app
description: Default stackfile
# template used to create the project
template: test_stack/node_project
# list of plugins to be applied after project creation
plugins:
  - plugin: test_stack/<plugin-name>
